import nuke
def IBKMy():
    try:
        n = nuke.selectedNode()
        x = n['xpos'].value()
        x = int(x)
        y = n['ypos'].value()
        y = int(y)
        dot = nuke.nodes.Dot()
        dot.setXYpos(x+35,y+80)
        dot.setInput(0,n)
        color = nuke.nodes.IBKColourV3()
        color.setXYpos(x,y+110)
        color.setInput(0,dot)
        x = color['xpos'].value()
        x = int(x)
        y = color['ypos'].value()
        y = int(y)
        dot3 = nuke.nodes.Dot()
        dot3.setXYpos(x-30,y-30)
        dot3.setInput(0,dot)
        dot2 = nuke.nodes.Dot()
        dot2.setXYpos(x-30,y+45)
        dot2.setInput(0,dot3)
        gizmo = nuke.nodes.IBKGizmoV3()
        gizmo.setXYpos(x,y+40)
        gizmo.setInput(1,color)
        gizmo.setInput(0,dot2)
    except:
        dotk = nuke.createNode("Dot")
        dotk.setSelected(True)
        n = nuke.selectedNode()
        x = n['xpos'].value()
        x = x-35
        x = int(x)
        y = n['ypos'].value()
        y = y-50
        y = int(y)
        dot = nuke.nodes.Dot()
        dot.setXYpos(x+35,y+80)
        dot.setInput(0,n)
        color = nuke.nodes.IBKColourV3()
        color.setXYpos(x,y+110)
        color.setInput(0,dot)
        x = color['xpos'].value()
        x = int(x)
        y = color['ypos'].value()
        y = int(y)
        dot3 = nuke.nodes.Dot()
        dot3.setXYpos(x-30,y-30)
        dot3.setInput(0,dot)
        dot2 = nuke.nodes.Dot()
        dot2.setXYpos(x-30,y+45)
        dot2.setInput(0,dot3)
        gizmo = nuke.nodes.IBKGizmoV3()
        gizmo.setXYpos(x,y+40)
        gizmo.setInput(1,color)
        gizmo.setInput(0,dot2)